version: '3.9'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: task_management
      MYSQL_ROOT_PASSWORD: ""  # It's better to set a root password in prod!
    ports:
      - "3307:3306"   # maps container 3306 to localhost 3307
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: ""
      DB_NAME: task_management
      DB_PORT: 3306

volumes:
  db_data:
